### ISSUE TITLE
[Feature request]: 希望增加一个选项：停止串流并关闭电脑设备

### ISSUE THREAD

**Issue by q15971095971** [qiin2333/moonlight-android#5]
### Is your feature request related to a problem? Please describe.

目前的设置是开始串流后，关闭主显示器，仅在虚拟显示器上显示。
冬天在被窝里结束串流后，还要起身去关闭电脑主机。如果在串流中从win菜单关闭电脑，下次电脑主机开机，显示设置会从原本的 仅在主显示器显示 变成 扩展显示。这里希望能保持原本的仅在主显示器显示，因为白天会在主显示器上玩游戏的需求。

### Describe the solution you'd like

增加一个结束串流并关闭电脑主机的选项

### Describe alternatives you've considered

增加一个结束串流并关闭电脑主机的选项

**Comment by qiin2333** [comment]
我希望你睡眠
